Add base case acceptance test
eclipse-pass/pass-acceptance-testing pull request #1
Opened 2022-09-30 22:30 UTC by frogfoot9013

First pass on the base case acceptance test with testcafe

2022-10-03 20:43 UTC, jabrah commented on tests/tests.js
> +        .doubleClick('#login-button')
I was running into issues where the login here wasn't working correctly. Changing these `doubleClick` calls to `click` fixed it for me -- Unless there is a reason to double click, IMO these double clicks in the login Roles should be changed to clicks

2022-10-03 20:43 UTC, jabrah commented on tests/tests.js
> +    var currLocation = ClientFunction(() => window.location.href);
The ClientFunction here can be specified outside of your test function and called any number of times like a "normal" function in the test. This would eliminate the reassignments of `currLocation` in the test function

``` javascript
const currLocation = ClientFunction(() => window.location.href);

test('', async (t) => {
  ...
  await t.expect(currLocation()).eql('...');
});
```

2022-10-03 20:43 UTC, jabrah commented on tests/tests.js
> +    await t.expect(nihGrant.innerText).eql('Eye research (07/01/2017 - 06/30/2022)');
A couple of things here:

* I'd consider this selector to be over-specified and can be simplified a bit. Mapping the deep child relationships in this way works now, but is pretty brittle. Instead we can a simpler CSS selector such as Selector(`#grants-selection-table td`).withText(...)
* These selectors were throwing errors for me because the dates. I was shown the dates: `(06/31/2017 - 06/29/2022)` -- Presumably there's some weirdness with timezones. It'll likely be easier to leave dates out of these checks. In this case, you'd have to change `withExactText` to `withText` and match on Eye research (or match on the Award Number) since withExactText will match the full text string of the selected element

2022-10-03 20:59 UTC, jaredgalanis commented on tests/tests.js
> +    await t.expect(nihGrant.innerText).eql('Eye research (07/01/2017 - 06/30/2022)');
I would also say that you might consider using the pattern that you used below on line 98 where you match some text in the selector and then test for that selected element's existence. Matching again on the innerText is a bit duplicative.

2022-10-04 21:21 UTC, frogfoot9013 commented on tests/tests.js
> +        .doubleClick('#login-button')
Fixed this now.

2022-10-04 21:21 UTC, frogfoot9013 commented on tests/tests.js
> +    var currLocation = ClientFunction(() => window.location.href);
Fixed now.

2022-10-04 21:22 UTC, frogfoot9013 commented on tests/tests.js
> +    await t.expect(nihGrant.innerText).eql('Eye research (07/01/2017 - 06/30/2022)');
The CSS selector you suggested there didn't seem to work with the tables but I think I've a suitable simplified selector now.

2022-10-07 12:21 UTC, frogfoot9013 commented on tests/tests.js
> +        .child('tbody').child('tr').child('td').withExactText('Eye research (07/01/2017 - 06/30/2022)');
Fixed now, I've switched it to using the grant award number.

2022-10-07 12:34 UTC, jaredgalanis requested changes

2022-10-07 12:34 UTC, jaredgalanis commented on tests/tests.js
> +    await t.expect(nihGrant.innerText).eql('Eye research (07/01/2017 - 06/30/2022)');
I think you might have missed my comment above. Here I would suggest: 
```suggestion
    await t.expect(nihGrant.exists).ok();
```

2022-10-07 12:41 UTC, frogfoot9013 commented on tests/tests.js
> +    await t.expect(nihGrant.innerText).eql('Eye research (07/01/2017 - 06/30/2022)');
I've changed it from the grant name to the grant award number instead, which also involves changing it to checking for exists as opposed to matching innerText, so I'm not sure how this should apply now.

2022-10-07 12:44 UTC, jaredgalanis commented on tests/tests.js
> +    await t.expect(nihGrant.innerText).eql('Eye research (07/01/2017 - 06/30/2022)');
Ah I think I was still looking at the state of the old file. That makes sense and looks good to me.

2022-10-07 12:44 UTC, jaredgalanis approved these changes

2022-10-10 13:12 UTC, merged