Add Proxy Submission Acceptance Tests
eclipse-pass/pass-acceptance-testing pull request #2
Opened 2022-10-17 13:42 UTC by frogfoot9013

Add acceptance tests for proxy submissions on behalf of submitter with and without a PASS account, rework the previous tests to split across multiple files for convenience.

2022-10-26 19:40 UTC, jabrah requested changes
Looking pretty good overall. Updating the timeouts to use environment variables can be a future update, but I think we should update the module format

2022-10-26 19:40 UTC, jabrah commented on tests/commonTest.js
> +module.exports = {
We should keep consistent module formats, so prefer ESM syntax. For example here, the `module.exports` should be removed in favor of `export const userIncompleteNih = ...`. In this example, we'd use `import` like `import { userIncompleteNih } from './commonTests';`

2022-10-26 19:40 UTC, jabrah commented on tests/proxySubmissionTests.js
> +    pageLoadTimeout:    60000,
Would be good to have timeouts configurable with environment variables, so we could change them in CI, for example, without a code change

2022-10-28 19:14 UTC, frogfoot9013 commented on tests/commonTest.js
> +module.exports = {
Fixed this.

2022-10-28 19:14 UTC, frogfoot9013 commented on tests/proxySubmissionTests.js
> +    pageLoadTimeout:    60000,
Not sure if I've done this the right way, I think I might need to have a different way of doing it.

2022-10-31 13:05 UTC, jaredgalanis approved these changes
Looks good to me 👍

2022-10-31 13:09 UTC, jaredgalanis commented
> Looks good to me 👍

So this approval was just based on a review of the code. If things aren't running well yet, I'll wait until you get there.

2022-10-31 14:43 UTC, jabrah reviewed
Ran tests with the command `TIMEOUT_LENGTH=30000 npx testcafe chrome tests/` successfully. Manually checking the timeout value in the tests showed that the value did respond to the environment variable fine.

One request: could you update the README to include some simple testing instructions, including a description of the environment variable(s) available

2022-10-31 14:43 UTC, jabrah commented on tests/commonTest.js
> +export const TIMEOUT_LENGTH = parseInt(process.env.TIMEOUT_LENGTH) || 60000;
I think for now, this is a fine way of reading in an environment variable.

If you need to add more environment variables down the line (such as for other Testcafe timeouts), then you might consider using a `.env` file with an NPM package like `dotenv`, but for that's more complexity than we need right now.

2022-11-01 20:27 UTC, frogfoot9013 commented on tests/baseCaseTests.js
> +}).disablePageCaching;
I don't actually think those removed timeouts seemed to do anything, at least in the context of what I was doing. I think they're for waiting for a page to load, as opposed to what I have been working with timeouts, which has been for getting a selector to wait for a particular element to appear (which is set when creating the Selector itself).

2022-11-04 13:12 UTC, jabrah approved these changes

2022-11-04 14:05 UTC, merged